2023-07-04 10:49:05,222 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-04 10:52:11,208 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2023-07-04 10:52:12,147 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-04 10:58:51,962 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2023-07-04 10:58:52,867 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 09:10:22,569 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 09:12:02,196 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2023-07-10 09:12:03,696 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 09:12:04,804 [ERROR] django.request: Internal Server Error: /en/shop/products/export/
Traceback (most recent call last):
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py", line 215, in get
    elem = products.data[0]
AttributeError: 'QuerySet' object has no attribute 'data'
2023-07-10 09:12:24,421 [ERROR] django.request: Internal Server Error: /en/shop/products/export/
Traceback (most recent call last):
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py", line 215, in get
    elem = products_data[0]
AttributeError: 'QuerySet' object has no attribute 'data'
2023-07-10 09:12:24,463 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2023-07-10 09:12:25,388 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 09:12:48,183 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2023-07-10 09:12:50,199 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 09:13:16,558 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2023-07-10 09:13:17,729 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 09:13:19,040 [ERROR] django.request: Internal Server Error: /en/shop/products/export/
Traceback (most recent call last):
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py", line 216, in get
    name = elem['nae']
KeyError: 'nae'
2023-07-10 09:20:42,559 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2023-07-10 09:20:43,531 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 09:20:56,403 [WARNING] django.request: Not Found: /favicon.ico
2023-07-10 09:20:59,810 [ERROR] django.request: Internal Server Error: /en/shop/products/export/
Traceback (most recent call last):
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py", line 216, in get
    name = elem['nae']
KeyError: 'nae'
2023-07-10 09:21:17,056 [ERROR] django.request: Internal Server Error: /en/shop/products/export/
Traceback (most recent call last):
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py", line 216, in get
    name = elem['nae']
KeyError: 'nae'
2023-07-10 09:22:39,892 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 09:22:46,373 [WARNING] django.request: Not Found: /favicon.ico
2023-07-10 09:22:49,074 [ERROR] django.request: Internal Server Error: /en/shop/products/export/
Traceback (most recent call last):
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py", line 216, in get
    name = elem['nae']
KeyError: 'nae'
2023-07-10 09:24:16,276 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2023-07-10 09:24:18,827 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 09:59:32,288 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 09:59:45,829 [WARNING] django.request: Not Found: /favicon.ico
2023-07-10 10:02:32,417 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2023-07-10 10:02:33,838 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 10:02:35,145 [ERROR] django.request: Internal Server Error: /en/admin/shopapp/product/
Traceback (most recent call last):
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: shopapp/product_change_list.html
2023-07-10 10:02:57,726 [ERROR] django.request: Internal Server Error: /en/admin/shopapp/product/
Traceback (most recent call last):
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: shopapp/product_change_list.html
2023-07-10 10:02:57,733 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2023-07-10 10:02:59,446 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 10:03:01,226 [ERROR] django.request: Internal Server Error: /en/admin/shopapp/product/
Traceback (most recent call last):
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 74, in resolve_template
    return get_template(template, using=self.using)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 200, in compile_nodelist
    return parser.parse()
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 513, in parse
    raise self.error(token, e)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/defaulttags.py", line 1372, in url
    viewname = parser.compile_filter(bits[1])
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''admin:import_products_csv' from ''admin:import_products_csv'
2023-07-10 10:12:57,675 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2023-07-10 10:12:59,085 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 10:24:55,636 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2023-07-10 10:24:57,329 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 10:49:48,522 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2023-07-10 10:49:49,651 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 10:55:17,200 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/admin.py changed, reloading.
2023-07-10 10:55:18,732 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 10:56:07,563 [ERROR] django.request: Internal Server Error: /en/admin/shopapp/product/import-products-csv/
Traceback (most recent call last):
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1715, in to_python
    return decimal.Decimal(value)
decimal.InvalidOperation: [<class 'decimal.ConversionSyntax'>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/mysite/shopapp/admin.py", line 99, in import_csv
    Product.objects.bulk_create(products)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 816, in bulk_create
    returned_columns = self._batched_insert(
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1817, in _batched_insert
    self._insert(
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/query.py", line 1791, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1659, in execute_sql
    for sql, params in self.as_sql():
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1583, in as_sql
    value_rows = [
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1584, in <listcomp>
    [
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1585, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1523, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1725, in get_db_prep_save
    self.to_python(value), self.max_digits, self.decimal_places
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1717, in to_python
    raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ["“ '2299.00'” value must be a decimal number."]
2023-07-10 11:01:44,908 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2023-07-10 11:01:45,981 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 11:10:45,145 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 11:23:24,554 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2023-07-10 11:23:26,743 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 11:23:37,797 [WARNING] django.request: Method Not Allowed: /en/shop/api/products/upload_csv/
2023-07-10 11:28:42,735 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/shopapp/views.py changed, reloading.
2023-07-10 11:28:43,722 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 11:34:34,355 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2023-07-10 11:34:35,183 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 11:45:51,093 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 11:47:29,531 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/secondblogapp/admin.py changed, reloading.
2023-07-10 11:47:31,213 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 11:47:32,605 [WARNING] django.request: Not Found: /
2023-07-10 11:48:30,385 [ERROR] django.request: Internal Server Error: /secondblog/articles/1/
Traceback (most recent call last):
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 38, in sentry_patched_render
    return old_render(self)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 75, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "/home/skillboxer/PycharmProjects/python_django/venv/lib/python3.10/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: secondblogapp/article_detail.html
2023-07-10 11:50:49,249 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 11:57:11,974 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/secondblogapp/views.py changed, reloading.
2023-07-10 11:57:12,897 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 12:11:18,142 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/mysite/urls.py changed, reloading.
2023-07-10 12:11:19,432 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-07-10 12:12:00,287 [INFO] django.utils.autoreload: /home/skillboxer/PycharmProjects/python_django/mysite/mysite/settings.py changed, reloading.
2023-07-10 12:12:01,014 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
